export const catalogoProdutos = [
  {
      codigoProduto: 1, 
      produto:" Camisa Argentina Away 22/23",
      preco: 149.70,
      parcela: "12 x de R$15,05",
      imagemProduto: "img/camisaArgentinaAway22_23.png",
      imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
      time: "Argentina",
      tipo: "Normal"
  },
  {
      codigoProduto: 2, 
      produto:" Camisa Argentina Home 22/23",
      preco: 149.70,
      parcela: "12 x de R$15,05",
      imagemProduto: "img/camisaArgentinaHome22_23.png",
      imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
      time: "Argentina",
      tipo: "Normal"
  },
  {
      codigoProduto: 3, 
      produto:" Camisa Arsenal Away 22/23",
      preco: 139.70,
      parcela: "12 x de R$14,03",
      imagemProduto: "img/camisaArsenalAway22_23.png",
      imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
      time: "Arsenal",
      tipo: "Normal"
  },
  {
      codigoProduto: 4, 
      produto:" Camisa Arsenal Away 23/24",
      preco: 149.70,
      parcela: "12 x de R$15,05",
      imagemProduto: "img/camisaArsenalAway23_24.png",
      imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
      time: "Arsenal",
      tipo: "Normal"
  },
  {
      codigoProduto: 5, 
      produto:" Camisa Arsenal Goleiro 23/24",
      preco: 143.70,
      parcela: "12 x de R$15,05",
      imagemProduto: "img/camisaArsenalGoleiro23_24.png",
      imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
      time: "Arsenal",
      tipo: "Normal"
  },
  {
      codigoProduto: 6, 
      produto:" Camisa Arsenal Home 22/23",
      preco: 149.70,
      parcela: "12 x de R$15,05",
      imagemProduto: "img/camisaArsenalHome22_23.png",
      imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
      time: "Arsenal",
      tipo: "Normal"
  },
  {
    codigoProduto: 7, 
    produto:" Camisa Arsenal Home 23/24",
    preco: 143.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaArsenalHome23_24.png",
    imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
    imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
    imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Arsenal",
    tipo: "Normal",
    mostrarHome:true
},
{
    codigoProduto: 8, 
    produto:" Camisa Arsenal Retrô 2005",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaArsenalRetrô2005_2006.png",
    imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
    imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
    imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Arsenal",
    tipo: "Retro"
},
{
    codigoProduto: 9, 
    produto:" Camisa Arsenal Treino 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaArsenalTreino23_24.png",
    imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
    imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
    imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Arsenal",
    tipo: "Normal"
},
{
    codigoProduto: 10, 
    produto:" Camisa Atletico de Madrid Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaAtleticoMadridHome22_23.png",
    imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
    imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
    imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "AtleticoMadrid",
    tipo: "Normal"
},
{
    codigoProduto: 11, 
    produto:" Camisa Atletico de Madrid Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaAtleticoMadridHome23_24.png",
    imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
    imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
    imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "AtleticoMadrid",
    tipo: "Normal"
},
{
    codigoProduto: 12, 
    produto:" Camisa Atletico Mineiro Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaAtléticoMineiroAway22_23.png",
    imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
    imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
    imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "AtleticoMineiro",
    tipo: "Normal"
},
{
    codigoProduto: 13, 
    produto:" Camisa Atletico Mineiro Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaAtléticoMineiroHome22_23.png",
    imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
    imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
    imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "AtleticoMineiro",
    tipo: "Normal"
},
{
    codigoProduto: 14, 
    produto:" Camisa Barcelona Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBarcelonaAway22_23.png",
    imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
    imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
    imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Barcelona",
    tipo: "Normal"
},
{
    codigoProduto: 15, 
    produto:" Camisa Barcelona Away 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBarcelonaAway23_24.png",
    imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
    imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
    imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Barcelona",
    tipo: "Normal"
},
{
    codigoProduto: 16, 
    produto:" Camisa Barcelona Black Classic 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBarcelonaBlackClassic23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Barcelona",
    tipo: "Normal"
},
{
    codigoProduto: 17, 
    produto:" Camisa Barcelona Home 14/15",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBarcelonaHome14_15.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
      time: "Barcelona",
    tipo: "Retro"
},
{
    codigoProduto: 18, 
    produto:" Camisa Barcelona Home 21/22",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBarcelonaHome21_22.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Barcelona",
    tipo: "Normal"
},
{
    codigoProduto: 19, 
    produto:" Camisa Barcelona Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBarcelonaHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Barcelona",
    tipo: "Normal",
    mostrarHome:true
},
{
    codigoProduto: 20, 
    produto:" Camisa Barcelona Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBarcelonaHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Barcelona",
    tipo: "Normal",
    lancamento:true
},
{
    codigoProduto: 21, 
    produto:" Camisa Barcelona Três 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBarcelonaTres22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Barcelona",
    tipo: "Normal"
},
{
    codigoProduto: 22, 
    produto:" Camisa Brasil Três 19/20",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBrasilAway 3 19_20.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Brasil",
    tipo: "Normal"
},
{
    codigoProduto: 23, 
    produto:" Camisa Brasil Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBrasilAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Brasil",
    tipo: "Normal"
},
{
    codigoProduto: 24, 
    produto:" Camisa Brasil Black Edition 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBrasilBlackEdition22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Brasil",
    tipo: "Normal"
},
{
    codigoProduto: 25, 
    produto:" Camisa Brasil Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaBrasilHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Brasil",
    tipo: "Normal",
    mostrarHome:true
},
{
    codigoProduto: 26, 
    produto:" Camisa Corinthians Três 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaCorinthiansAway 3 22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Corinthians",
    tipo: "Normal",
},
{
    codigoProduto: 27, 
    produto:" Camisa Corinthians Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaCorinthiansAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Corinthians",
    tipo: "Normal"
},
{
    codigoProduto: 28, 
    produto:" Camisa Corinthians Away 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaCorinthiansAway23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Corinthians",
    tipo: "Normal",
    mostrarHome:true
},
{
    codigoProduto: 29, 
    produto:" Camisa Corinthians Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaCorinthiansHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Corinthians",
    tipo: "Normal"
},
{
    codigoProduto: 30, 
    produto:" Camisa Corinthians Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaCorinthiansHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Corinthians",
    tipo: "Normal",
    mostrarHome:true,
    lancamento:true
},
{
    codigoProduto: 31, 
    produto:" Camisa Corinthians Retrô 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaCorinthiansRetrô23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Corinthians",
    tipo: "Retro"
},
{
    codigoProduto: 32, 
    produto:" Camisa Corinthians Treino 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaCorinthiansTreino22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Corinthians",
    tipo: "Normal"
},
{
    codigoProduto: 33, 
    produto:" Camisa Espanha Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaEspanhaAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Espanha",
    tipo: "Normal"
},
{
    codigoProduto: 34, 
    produto:" Camisa Espanha Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaEspanhaHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Espanha",
    tipo: "Normal"
    
},
{
    codigoProduto: 35, 
    produto:" Camisa Flamengo Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaFlamengoAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Flamengo",
    tipo: "Normal"
},
{
    codigoProduto: 36, 
    produto:" Camisa Flamengo Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaFlamengoHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Flamengo",
    tipo: "Normal"
},
{
    codigoProduto: 37, 
    produto:" Camisa Flamengo Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaFlamengoHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Flamengo",
    tipo: "Normal",
    lancamento:true
},
{
    codigoProduto: 38, 
    produto:" Camisa Flamengo Retrô 2008",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaFlamengoRetrô2008_2009.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Flamengo",
    tipo: "Retrô"
},
{
    codigoProduto: 39, 
    produto:" Camisa França Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaFrancaAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "França",
    tipo: "Normal"
},
{
    codigoProduto: 40, 
    produto:" Camisa França Retrô 1998",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisafrancaAwayRetrô1998.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "França",
    tipo: "Retro"
},
{
    codigoProduto: 41, 
    produto:" Camisa França Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaFrancaHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "França",
    tipo: "Normal"
},
{
    codigoProduto: 42, 
    produto:" Camisa Inglaterra Especial 21/22",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInglaterraEspecial21_22.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Inglaterra",
    tipo: "Normal"
},
{
    codigoProduto: 43, 
    produto:" Camisa Inglaterra Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInglaterraHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Inglaterra",
    tipo: "Normal"
},
{
    codigoProduto: 44, 
    produto:" Camisa Inter de Milão Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInterMilaoAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "InterMilao",
    tipo: "Normal"
},
{
    codigoProduto: 45, 
    produto:" Camisa Inter de Milão Away 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInterMilaoAway23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "InterMilao",
    tipo: "Normal",
    
},
{
    codigoProduto: 46, 
    produto:" Camisa Inter de Milão Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInterMilaoHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "InterMilao",
    tipo: "Normal"
},
{
    codigoProduto: 47, 
    produto:" Camisa Inter de Milão Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInterMilaoHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "InterMilao",
    tipo: "Normal",
    lancamento:true
},
{
    codigoProduto: 48, 
    produto:" Camisa Internacional Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInternacionalAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Internacional",
    tipo: "Normal"
},
{
    codigoProduto: 49, 
    produto:" Camisa Internacional Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInternacionalHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Internacional",
    tipo: "Normal"
},
{
    codigoProduto: 50, 
    produto:" Camisa Internacional Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInternacionalHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Internacional",
    tipo: "Normal"
},
{
    codigoProduto: 51, 
    produto:" Camisa Internacional Treino 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaInternacionalTreino23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Internacional",
    tipo: "Normal"
},
{
    codigoProduto: 52, 
    produto:" Camisa Liverpool Dois 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaLiverpooDois22_22.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Liverpool",
    tipo: "Normal"
},
{
    codigoProduto: 53, 
    produto:" Camisa Liverpool Away 21/22",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaLiverpoolAway21_22.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Liverpool",
    tipo: "Normal"
},
{
    codigoProduto: 54, 
    produto:" Camisa Liverpool Away 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaLiverpoolAway23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Liverpool",
    tipo: "Normal"
},
{
    codigoProduto: 55, 
    produto:" Camisa Liverpool Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaLiverpoolHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Liverpool",
    tipo: "Normal"
},
{
    codigoProduto: 56, 
    produto:" Camisa Liverpool Retrô 2006",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaLiverpooRetro2006_2007.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Liverpool",
    tipo: "Retro"
},
{
    codigoProduto: 57, 
    produto:" Camisa Liverpool Retrô 2007",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaLiverpooRetro2007_2008.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Liverpool",
    tipo: "Retro"
},
{
    codigoProduto: 58, 
    produto:" Camisa Liverpool Três 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaLiverpooTres22_22.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Liverpool",
    tipo: "Normal"
},
{
    codigoProduto: 59, 
    produto:" Camisa Manchester City Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterCityAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterCity",
    tipo: "Normal"
},

{
    codigoProduto: 60, 
    produto:" Camisa Manchester City Away 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterCityAway23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterCity",
    tipo: "Normal"
},

{
    codigoProduto: 61, 
    produto:" Camisa Manchester City Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterCityHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterCity",
    tipo: "Normal"
},

{
    codigoProduto: 62, 
    produto:" Camisa Manchester City Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterCityHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterCity",
    tipo: "Normal"
},

{
    codigoProduto: 63, 
    produto:" Camisa Manchester City Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterCityHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterCity",
    tipo: "Normal"
},

{
    codigoProduto: 64, 
    produto:" Camisa Manchester City Special Edition 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterCitySpecialEdition23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterCity",
    tipo: "Normal"
},

{
    codigoProduto: 65, 
    produto:" Camisa Manchester United Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterUnitedAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterUnited",
    tipo: "Normal"
},

{
    codigoProduto: 66, 
    produto:" Camisa Manchester United Away 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterUnitedAway23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterUnited",
    tipo: "Normal"
},

{
    codigoProduto: 67, 
    produto:" Camisa Manchester United Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterUnitedHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterUnited",
    tipo: "Normal"
},

{
    codigoProduto: 68, 
    produto:" Camisa Manchester United Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaManchesterUnitedHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "ManchesterUnited",
    tipo: "Normal",
    lancamento:true
},

{
    codigoProduto: 69, 
    produto:" Camisa Milan Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaMilanAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Milan",
    tipo: "Normal"
},

{
    codigoProduto: 70, 
    produto:" Camisa Milan Away Retrô 2007",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaMilanAwayRetro2007.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Milan",
    tipo: "Retro"
},

{
    codigoProduto: 71, 
    produto:" Camisa Milan Especial 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaMilanEspecial23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Milan",
    tipo: "Normal"
},

{
    codigoProduto: 72, 
    produto:" Camisa Milan Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaMilanHome22_23.png",
          imagemProduto2: "img/produto/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/produto/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/produto/camisaMilanHome22_23Pos4.png",
    time: "Milan",
    tipo: "Normal",
    mostrarHome:true
},

{
    codigoProduto: 73, 
    produto:" Camisa Milan Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaMilanHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Milan",
    tipo: "Normal"
},

{
    codigoProduto: 74, 
    produto:" Camisa Milan Home Retrô 1993",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaMilanHomeRetro1993.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Milan",
    tipo: "Retro"
},

{
    codigoProduto: 75, 
    produto:" Camisa Milan Home Retrô 2007",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaMilanHomeRetro2007.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Milan",
    tipo: "Retro"
},

{
    codigoProduto: 76, 
    produto:" Camisa Milan Retrô Comemorativa 2007",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaMilanRetroComemorativa2007.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Milan",
    tipo: "Retro"
},

{
    codigoProduto: 77, 
    produto:" Camisa Napoli Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaNapoliAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Napoli",
    tipo: "Normal"
},

{
    codigoProduto: 78, 
    produto:" Camisa Napoli Especial 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaNapoliEspecial22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Napoli",
    tipo: "Normal"
},

{
    codigoProduto: 79, 
    produto:" Camisa Napoli Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaNapoliHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Napoli",
    tipo: "Normal"
},

{
    codigoProduto: 80, 
    produto:" Camisa Napoli Retrô 1991",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaNapoliRetro91_93.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Napoli",
    tipo: "Retro"
},

{
    codigoProduto: 81, 
    produto:" Camisa Palmeiras Away 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPalmeirasAway23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Palmeiras",
    tipo: "Normal"
},

{
    codigoProduto: 82, 
    produto:" Camisa Palmeiras Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPalmeirasHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Palmeiras",
    tipo: "Normal"
},

{
    codigoProduto: 83, 
    produto:" Camisa Portugal Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPortugalAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Portugal",
    tipo: "Normal"
},

{
    codigoProduto: 84, 
    produto:" Camisa Portugal Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPortugalHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Portugal",
    tipo: "Normal"
},

{
    codigoProduto: 85, 
    produto:" Camisa PSG Quatro 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPsgAway 4 22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "PSG",
    tipo: "Normal"
},

{
    codigoProduto: 86, 
    produto:" Camisa PSG Away 21/22",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPsgAway21_22.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "PSG",
    tipo: "Normal"
},

{
    codigoProduto: 87, 
    produto:" Camisa PSG Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPsgAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "PSG",
    tipo: "Normal"
},

{
    codigoProduto: 88, 
    produto:" Camisa PSG Dois 21/22",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPsgDois21_22.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "PSG",
    tipo: "Normal"
},

{
    codigoProduto: 89, 
    produto:" Camisa PSG Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPSGHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "PSG",
    tipo: "Normal",
    mostrarHome:true
},

{
    codigoProduto: 90, 
    produto:" Camisa PSG Quatro 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPSGQuatro23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "PSG",
    tipo: "Normal"
},

{
    codigoProduto: 91, 
    produto:" Camisa PSG Refletiva 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPSGRefletiva23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "PSG",
    tipo: "Normal",
    mostrarHome:true
},

{
    codigoProduto: 92, 
    produto:" Camisa PSG Refletiva Dois 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPSGRefletivaDois23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "PSG",
    tipo: "Normal"
},

{
    codigoProduto: 93, 
    produto:" Camisa PSG Treino 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaPSGTreino23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "PSG",
    tipo: "Normal",
    lancamento:true
},

{
    codigoProduto: 94, 
    produto:" Camisa Real Madrid Away 21/22",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRealAway21_22.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Real",
    tipo: "Normal"
},

{
    codigoProduto: 95, 
    produto:" Camisa Real Madrid Away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRealAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Real",
    tipo: "Normal"
},

{
    codigoProduto: 96, 
    produto:" Camisa Real Madrid Away 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRealAway23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Real",
    tipo: "Normal"
},

{
    codigoProduto: 97, 
    produto:" Camisa Real Madrid Especial 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRealEspecial22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Real",
    tipo: "Normal"
},

{
    codigoProduto: 98, 
    produto:" Camisa Real Madrid Especial 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRealEspecial23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Real",
    tipo: "Normal"
},

{
    codigoProduto: 99, 
    produto:" Camisa Real Madrid Home 21/22",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRealHome21_22.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Real",
    tipo: "Normal"
},

{
    codigoProduto: 100, 
    produto:" Camisa Real Madrid Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRealHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Real",
    tipo: "Normal"
},

{
    codigoProduto: 101, 
    produto:" Camisa Real Madrid Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRealHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Real",
    tipo: "Normal",
    lancamento:true
},

{
    codigoProduto: 102, 
    produto:" Camisa Real Madrid Retrô 2017",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRealRetro2017.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Real",
    tipo: "Retro"
},

{
    codigoProduto: 103, 
    produto:" Camisa Roma Away 20/21",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRomaAway20_21.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Roma",
    tipo: "Normal"
},

{
    codigoProduto: 104, 
    produto:" Camisa Roma Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRomaHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Roma",
    tipo: "Normal"
},

{
    codigoProduto: 105, 
    produto:" Camisa Roma Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaRomaHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Roma",
    tipo: "Normal",
    lancamento:true
},

{
    codigoProduto: 106, 
    produto:" Camisa Santos Três 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaSantosAway 3 23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Santos",
    tipo: "Normal"
},

{
    codigoProduto: 107, 
    produto:" Camisa Santos Away 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaSantosAway23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Santos",
    tipo: "Normal"
},

{
    codigoProduto: 108, 
    produto:" Camisa Santos Home 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaSantosHome23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Santos",
    tipo: "Normal"
},
{
    codigoProduto: 109, 
    produto:" Camisa Santos Treino 23/24",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaSantosTreino23_24.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Santos",
    tipo: "Normal"
},

{
    codigoProduto: 110, 
    produto:" Camisa São Paulo away 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaSaoPauloAway22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "SaoPaulo",
    tipo: "Normal"
},

{
    codigoProduto: 111, 
    produto:" Camisa São Paulo Home 22/23",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/camisaSaoPauloHome22_23.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "SaoPaulo",
    tipo: "Normal"
},

{
    codigoProduto: 112, 
    produto:" Corta Vento Arsenal Vermelho",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/cortaVentoArsenalVermelho.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Arsenal",
    tipo: "CortaVento"
},

{
    codigoProduto: 113, 
    produto:" Corta Vento Corinthians Preto",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/cortaVentoCorinthiansPreto.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Corinthians",
    tipo: "CortaVento"
},

{
    codigoProduto: 114, 
    produto:" Corta Vento Liverpool Branca",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/cortaVentoLiverpoolBranca.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Liverpool",
    tipo: "CortaVento"
},

{
    codigoProduto: 115, 
    produto:" Corta Vento Roma Vermelho",
    preco: 149.70,
    parcela: "12 x de R$15,05",
    imagemProduto: "img/cortaVentoRomaVermelho.png",
          imagemProduto2: "img/camisaMilanHome22_23Pos2.png",
      imagemProduto3: "img/camisaMilanHome22_23Pos3.png",
      imagemProduto4: "img/camisaMilanHome22_23Pos4.png",
    time: "Roma",
    tipo: "CortaVento"
},

]